### ISSUE TITLE
Swift-Kuery-SQLite not available

### ISSUE THREAD

**Issue by eugeniobaglieri** [IBM-Swift/Swift-Kuery#106]
I know, this is the wrong place, but why is Swift-Kuery-SQLite no more available?

**Comment by dingwilson** [comment]
Hey @eugeniobaglieri, we have deprecated several less-used libraries, including Swift-Kuery-SQLite, to be able to devote more time to maintaining and improving our more-used repos. You can read more information about this (as well as get a list of deprecated repos) at our [Swift@IBM Engineering Blog Post](https://developer.ibm.com/swift/2017/09/07/deprecation-less-used-repos/).

**Comment by eugeniobaglieri** [comment]
Ok, thank you
