### ISSUE TITLE
Can't build from command line: Swift 4, Xcode 9

### ISSUE THREAD

**Issue by dbecker215** [IBM-Swift/Swift-Kuery#107]
I’m having trouble getting a project to build once I add Swift-Kuery to the package manager (I’m looking to connect to Postgres). I used the Kitura sample, https://github.com/IBM-Swift/iOSSampleKituraKit, and it built fine with the default settings. I then added the package for https://github.com/IBM-Swift/Swift-Kuery and then it will no longer build. When I run `swift build --verbose` on it looks as though it’s just in a loop. Do I have the package and targets set up correctly?

I’m on `Swift 4` and `Xcode 9.0.1`.  And my `Package.swift` is below:

```swift
// swift-tools-version:4.0

import PackageDescription

let package = Package(
    name: "ToDoServer",
    dependencies: [
        .package(url: "https://github.com/IBM-Swift/Kitura.git", .upToNextMinor(from: "2.0.0")),
        .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", .upToNextMinor(from: "1.7.1")),
        .package(url: "https://github.com/IBM-Swift/CloudEnvironment.git", .upToNextMinor(from: "4.0.5")),
        .package(url: "https://github.com/RuntimeTools/SwiftMetrics.git", .upToNextMinor(from: "2.0.0")),
        .package(url: "https://github.com/IBM-Swift/Health.git", from: "0.0.0"),
        .package(url: "https://github.com/IBM-Swift/Kitura-CORS", .upToNextMinor(from: "2.0.0")),
        .package(url:"https://github.com/IBM-Swift/Swift-Kuery.git", from: "1.0.0")
        ],
    targets: [
        .target(name: "ToDoServer", dependencies: [ .target(name: "Application"), "Kitura" , "HeliumLogger"]),
        .target(name: "Application", dependencies: [ "Kitura", "KituraCORS", "CloudEnvironment", "Health" , "SwiftMetrics", "SwiftKuery"]),
        ]
)`

**Comment by EnriqueL8** [comment]
Hey @dbecker215 , are you still failing to build?

**Comment by dukhovnyi** [comment]
Hey, I have a similar problem with Xcode 9.3 and Swift 4.1.

When I try to execute `swift build` a get error with this stack:

`
Compile Swift Module 'SwiftKueryPostgreSQL' (6 sources)
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/~user~/Developer/personal/md/.build/checkouts/CLibpq.git-116411655460928350/shim.h:21:9: error: 'libpq-fe.h' file not found
#import <libpq-fe.h>
        ^
/Users/~user~/Developer/personal/md/.build/checkouts/Swift-Kuery-PostgreSQL-7200958270471261832/Sources/SwiftKueryPostgreSQL/PostgreSQLConnection.swift:18:8: error: could not build Objective-C module 'CLibpq'
import CLibpq
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/~user~/Developer/personal/md/.build/checkouts/CLibpq.git-116411655460928350/shim.h:21:9: error: 'libpq-fe.h' file not found
#import <libpq-fe.h>
        ^
/Users/~user~/Developer/personal/md/.build/checkouts/Swift-Kuery-PostgreSQL-7200958270471261832/Sources/SwiftKueryPostgreSQL/PostgreSQLConnection.swift:18:8: error: could not build Objective-C module 'CLibpq'
import CLibpq
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/~user~/Developer/personal/md/.build/checkouts/CLibpq.git-116411655460928350/shim.h:21:9: error: 'libpq-fe.h' file not found
#import <libpq-fe.h>
        ^
/Users/~user~/Developer/personal/md/.build/checkouts/Swift-Kuery-PostgreSQL-7200958270471261832/Sources/SwiftKueryPostgreSQL/PostgreSQLConnection.swift:18:8: error: could not build Objective-C module 'CLibpq'
import CLibpq
       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/~user~/Developer/personal/md/.build/checkouts/CLibpq.git-116411655460928350/shim.h:21:9: error: 'libpq-fe.h' file not found
#import <libpq-fe.h>
        ^
/Users/~user~/Developer/personal/md/.build/checkouts/Swift-Kuery-PostgreSQL-7200958270471261832/Sources/SwiftKueryPostgreSQL/PostgreSQLConnection.swift:18:8: error: could not build Objective-C module 'CLibpq'
import CLibpq
       ^
error: terminated(1): /Library/Developer/CommandLineTools/usr/bin/swift-build-tool -f /Users/~user~/Developer/personal/md/.build/debug.yaml main output:
`

Package.swift is

```
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "md",
    dependencies: [
        .package(url: "https://github.com/IBM-Swift/Kitura.git", .upToNextMinor(from: "2.3.0")),
        .package(url: "https://github.com/IBM-Swift/HeliumLogger.git", .upToNextMinor(from: "1.7.1")),
        .package(url: "https://github.com/IBM-Swift/CloudEnvironment.git", from: "7.1.0"),
        .package(url: "https://github.com/RuntimeTools/SwiftMetrics.git", from: "2.0.0"),
        .package(url: "https://github.com/IBM-Swift/Health.git", from: "1.0.0"),
        .package(url: "https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL.git", from: "1.0.0"),
        ],
    targets: [
        .target(name: "md",
                dependencies: [ .target(name: "Application"),
                                "Kitura",
                                "HeliumLogger",
                                "SwiftKueryPostgreSQL"
        ]),

        .target(name: "Application",
                dependencies: ["Kitura",
                               "CloudEnvironment",
                               "SwiftMetrics",
                               "Health"
        ]),

        .testTarget(name: "ApplicationTests" ,
                    dependencies: [.target(name: "Application"),
                                   "Kitura",
                                   "HeliumLogger"
        ])
    ]
)
`

**Comment by kilnerm** [comment]
Given Enrique already followed up and got no response I will mark this as closed. If there is still an issue we can reopen the issue.
