### ISSUE TITLE
fail to  use TRANSACTION   insert tow contingency table

### ISSUE THREAD

**Issue by ranshon** [IBM-Swift/Swift-Kuery#111]
BEGIN;

insert into users (user_id,name,idNo,telNo)  VALUES ('10','yyy','123','45799') returning user_id;

INSERT INTO rechargeTable (user_id, money) VALUES ('10', 0)returning recharge_id;

COMMIT;
the second sql is not effective in fact

**Comment by ianpartridge** [comment]
I'm sorry, I don't understand the problem you're reporting.  Can you be more descriptive and include some code as well?

**Comment by ranshon** [comment]
I want Implement this function that I descript in sql.  you can try it 。

**Comment by ianpartridge** [comment]
Can you provide your Swift code using Kuery?

**Comment by ranshon** [comment]
func addUser(userName name: String, idNo:String, telNo: String, rechargeMoney money :Int = 0,completion: @escaping (Error?) -> ()) {
        
        let connection = createConnection()
        
        let insertUser = Insert(into: Database.usersTable,columns: [Database.usersTable.userName,Database.usersTable.idNo,Database.usersTable.telNo],values: [name,idNo,telNo])
        do {
            let insertUserSql = try connection.descriptionOf(query: insertUser).appending("returning user_id")
            
            connection.connect { conError in
                
                if let conError = conError {
                    completion(conError)
                    connection.closeConnection()
                }
                connection.startTransaction(onCompletion: { startTranResult in
                    if startTranResult.success {
                        
                        connection.execute(insertUserSql, onCompletion: { insertResult in
                            if insertResult.success {
                                
                                if let resultSet = insertResult.asResultSet {
                                    for row in resultSet.rows {
                                        
                                        let insertRecharge = Insert(into: Database.rechargeTable,columns: [Database.rechargeTable.userID,Database.rechargeTable.money],values: [row[0]!,money])
                                        
                                        insertRecharge.execute(connection, onCompletion: { rechargeResult in
                                            
                                            if rechargeResult.success {
                                                connection.commit(onCompletion: { commitResult in
                                                    if commitResult.success {
                                                        connection.closeConnection()
                                                    }else {
                                                        connection.closeConnection()
                                                        completion(commitResult.asError!)
                                                    }
                                                })
                                            }else {
                                                connection.rollback(onCompletion: { rollBack in
                                                    connection.closeConnection()
                                                })
                                                connection.closeConnection()
                                            }
                                        })
                                    }
                                }
                            }else {
                                connection.closeConnection()
                                completion(insertResult.asError!)
                            }
                        })
                        
                        
                    }else {
                        connection.closeConnection()
                        completion(startTranResult.asError!)
                    }
                })
            }
            
        } catch  {
            connection.closeConnection()
            completion(error)
        }
    }

**Comment by ianpartridge** [comment]
Thanks. Kuery does not support the `RETURNING` clause.

**Comment by ranshon** [comment]
but i can get the value in fact 。  " insertRecharge.execute(connection, onCompletion: { rechargeResult in ..."  this code return sucess, but in DB I can not find the data.

**Comment by ranshon** [comment]
I use postgresql.  when i write the code that sequential execution not in  block . this function is ok

**Comment by ranshon** [comment]
Kuery  support the RETURNING clause。you can try

**Comment by kilnerm** [comment]
Hi @ranshon, did you ever get this working? I'll be happy to dig into it a little more if you still require some assistance.

**Comment by kilnerm** [comment]
I am going to close this issue, if you wish to follow up please reopen it.
