### ISSUE TITLE
Improve creation of rows with database assigned ids

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/Swift-Kuery#114]
**Background and problem definition**
It is a very common pattern to define a table with an **auto-incrementing primary key** used to define a unique database-assigned identifier for each row.

When creating such rows the user often wants to know the value of the **id** assigned for each new row created.

Currently SwiftKuery does not have an easy database-agnostic way of providing this information.

It is possible to get the information by performing a database-specific query (eg `SELECT LAST_INSERT_ID() FROM TABLE` in mysql) or query-modification (eg adding `RETURNING (id)` in Postgresql). However, this pushes the burden of knowledge on to the programmer despite this being a pattern that most (all?) SQL databases support, albeit in different ways (sadly, SQL doesn't standardize this).

**Goal**
This issue covers enhancing the SwiftKuery protocol to require implementations provide a way to get the value of the primary key for an inserted row.

**Notes/design questions**
- How would batch insertion work with this? (the ability to insert multiple rows in one INSERT-statement)
- Should we offer to return other fields than the primary key? (as Postgres RETURNING allows)
- How do the different DB implementations affect the way the API should look? (eg should allow implementations that require a modification of the INSERT statement, vs requiring a separate query)
- Are there any DB implementations that would make this difficult or impossible to implement? What should we do in those cases (examine why this is not supported, is it not a relevant technique for this DB or is there an alternative way it solves the use case?)
- What might an ORM built on SwiftKuery need in terms of the API? (an ORM will likely be working with less concrete information as it provides a general solution to persistence vs a specific application using SwiftKuery directly)

**Comment by EnriqueL8** [comment]
This can be closed :)
