### ISSUE TITLE
How to execute a raw query with parameters?

### ISSUE THREAD

**Issue by thedarkdima** [IBM-Swift/Swift-Kuery#131]
I am executing a lot of raw queries but sadly they can be injected, so I wanted to fix them but found out than the Execute a raw query with parameters doesn't work for me, as if it doesn't trying to enter the parameters into the query.

`var par = "dima"
dbConnection.execute("SELECT * FROM users WHERE users.username = ?1", parameters: [par], onCompletion: {result in
            if result.success{
                print("yey")
            }
        })`

syntaxError = "ERROR 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'?1\' at line 1"

I guess the problem in the ?1 but no matter where I look I couldn't find a example that works with raw execute so I copied from a normal execute, but I guess their foundation are completely different and because of that it doesn't work. Can you please show me an example of an Execute a raw query with parameters as it should be. 

Thanks Dima.

**Comment by kilnerm** [comment]
Hi @thedarkdima, 

Apologies for how long it has taken to respond to this issue. Below is an example of using a raw query with parameters on MySQL:

```
let raw = "UPDATE " + packName(t.tableName) + " SET a = 'banana', b = ? WHERE a = ?"
executeRawQueryWithParameters(raw, connection: connection, parameters: [4, "peach"])
```

In the example any row with the value 'peach' in column a will be update to contain a = 'banana' b = 4.

Hopefully this is helpful, let me know if you have further questions.

**Comment by kilnerm** [comment]
I'm marking this issue as closed, please reopen if you have follow up questions.
