### ISSUE TITLE
Check if table exists on creation

### ISSUE THREAD

**Issue by eugeniobaglieri** [IBM-Swift/Swift-Kuery#134]
What about add a check on table creation? At the moment the query is created with:

```
var query = "CREATE TABLE " + Utils.packName(_name, queryBuilder: queryBuilder)
```

I think it would better with

```
var query = "CREATE TABLE IF NOT EXISTS " + Utils.packName(_name, queryBuilder: queryBuilder)
```
So if the database change, tables can be recreated safely

**Comment by kilnerm** [comment]
The current behavior of Table.create would result in an error being returned if a table already exists. The benefit of returning the error is that it can be handled gracefully and used as an indication that the table is present or in the case where no error is thrown that the table is not present.

If we were to remove the error then there would be no way to know whether you had just created a new table or were using an existing one.

@eugeniobaglieri can you let me know your thoughts on this, thanks?

**Comment by kilnerm** [comment]
I'm going to mark this as closed, please re-open if you wish to follow up on the issue.
