### ISSUE TITLE
Swift-Kuery should throw an exception before it attempts to execute poorly formed SQL

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Swift-Kuery#14]
We forgot to change

```swift
class A: Table {
   let name = "A"
}
```

to:

```swift
class A: Table {
   let tableName = "A"
}
```

when we did an insert, it attempted to execute:

```sql 
INSERT into (id, ...) VALUES (..., )
```

Notice the missing tableName. We had to read the SQL error description in order to find out what was wrong. I am wondering if we can do some Swift API language tricks to ensure that this cannot be the case.

For instance, make `tableName` a required property in a protocol that Table uses. 

```swift
var tableName: String { get }
```

**Comment by irar2** [comment]
@rfdickerson I added a check in Table.build and Column.build that the table name is not "". Does this solve the problem?

**Comment by rfdickerson** [comment]
I suppose that works for now. I think an ideal solution would be to have compile-time guarantees through the language that tableName has been created. 

Also, have we considered having `columns` and `tableName` as required properties for a Table? Then you would define it like:


```swift
struct UsersTable: Table {

     var tableName = "users"

     let id = Column(name: "id", .integer, primaryKey: true,
     let name = Column(name: "name", .text)
  
    var columns = [ self.id, self.name ]

}
```

**Comment by shmuelk** [comment]
But Table is a class and not a protocol. If we added some protocol we would be required to add tableName and columns in Table as well which would defeat your entire idea here.

In any event requiring those fields doesn't help. Columns could be an empty array and tableName could be an empty String. These are things you can't detect at compile time.
