### ISSUE TITLE
Swift build wont succeed

### ISSUE THREAD

**Issue by askari01** [IBM-Swift/Swift-Kuery#150]
swift build is stuck for very long time. i have tried to initiate it multiple times, but it never completes.
it pauses downloading temporary files.shift -fileno 6

**Comment by kilnerm** [comment]
Hi @askari01, sorry it has taken so long to respond. Are you still experiencing the issue you reported?

**Comment by kilnerm** [comment]
I'm going to mark this as closed, please reopen if you require further help.
