### ISSUE TITLE
Connection management?

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Swift-Kuery#16]
Right now I have for each Kitura handler, creating a new PostgreSQL connection, connecting to it, then servicing the request. I would like to perhaps use a single connection object that can do a reconnect only if needed (in case the connection has been lost for some reason). Do do that, I need connection status. Perhaps the result of running:

```c
ConnStatusType PQstatus(const PGconn *conn);
```

https://www.postgresql.org/docs/9.1/static/libpq-status.html

Do we have plans for these find of connection management policies?

**Comment by irar2** [comment]
Here is a proposed API for connection pooling:

(`Pool` will be a slightly modified @djones6's implementation of [object pool](https://github.com/djones6/Swift-TechEmpower/blob/master/kitura/Sources/TechEmpowerPsqlPool/Pool.swift)).

```swift
public class ConnectionPool {
    private let pool: Pool<Connection> 
    
    public init(initialCapacity: Int, maxCapacity: Int = 0, timeout: Int = 0, connectionGenerator: @escaping () -> Connection?, connectionReleaser: @escaping (Connection) -> ()) { }
    
    deinit {  disconnect()  }
   
    public func getConnection() -> Connection? {}
    func release(connection: Connection) { }
    public func disconnect() {}
}
```
The plugins will create an instance of ConnectionPool with database specific connection generators and releasers.

getConnection() will return a ConnectionPoolConnection - a wrapper around the actual connection. The main purpose of this is to automatically release connection using ConnectionPoolConnection.deinit:
```swift
public class ConnectionPoolConnection: Connection {
   private var connection: Connection?
   private weak var pool: ConnectionPool?
    
   init(connection: Connection, pool: ConnectionPool) { }
    
   deinit {
        if let connection = connection {
            pool?.release(connection: connection)
        }
    }
   
   public func connect(onCompletion: (QueryError?) -> ()) { }
    
    public func closeConnection() {
        if let connection = connection {
            pool?.release(connection: connection)
            self.connection = nil
        }
    }
    
    public var isConnected: Bool {
        return connection != nil
    }
    
    public func execute(query: Query, onCompletion: @escaping ((QueryResult) -> ())) {
        connection?.execute(query: query, onCompletion: onCompletion)
    }
  
    // Other Connection functions.
}
```

We have to decide what to do if the connection is released and e.g. connection.execute() is called. I'll open a separate issue to discuss this.
