### ISSUE TITLE
MySQLThreadSafeConnection on version 3.0.0

### ISSUE THREAD

**Issue by fabrijp** [IBM-Swift/Swift-Kuery#172]
Hello.

On MySQLConnection.swift we have the below comments on line 23:

`An implementation of SwiftKuery.Connection protocol for MySQL.
Instances of MySQLConnection are NOT thread-safe and should not be shared between threads.
Use MySQLThreadSafeConnection to share connection instances between multiple threads.`

but can't find `MySQLThreadSafeConnection` on version 3.0.0

So all connections are now thread safe ?

**Comment by kilnerm** [comment]
@fabrijp This was a good spot that we missed in our reviews. The comment should be updated to reflect the current MySQLConnection implementation, I have an open PR on our MySQL repository to do this:    https://github.com/IBM-Swift/SwiftKueryMySQL/pull/47

MySQLConnection instances are still not thread safe however should you wish to share connections across threads we recommend that you use a ConnectionPool as it will handle the intricacies of ensuring multiple operations do not run concurrently on a connection. The MySQL plugin has also been updated to ensure a connection can be used on any thread.

The PR referenced previously will contain a Readme update that adds sample code illustrating our recommendation.

**Comment by kilnerm** [comment]
@fabrijp, https://github.com/IBM-Swift/SwiftKueryMySQL/pull/47 is now merged and the updated README with example code is live.

I am going to mark this as closed, feel free to reopen if you have any follow up questions.
