### ISSUE TITLE
ODBC Support

### ISSUE THREAD

**Issue by richardpauljones** [IBM-Swift/Swift-Kuery#179]
It would be really useful to add ODBC support to Swift-Kuery.

I work in the Enterprise space so Oracle/MS SQL/Excel etc. etc. Connectivity would be really welcome.

ODBC would be the answer

**Comment by richardpauljones** [comment]
Adding ODBC support to Swift-Kuery would also be compelling as it ODBC is supported by such projects such as UNIXODBC which has commitment to support Mac and Linux going forward.    These seems to marry nicely to the ambitions of Kitura.

**Comment by richardpauljones** [comment]
Not sure why this was closed.

**Comment by kilnerm** [comment]
I am closing this issue as @richardpauljones has published his work to date on adding support here:

https://github.com/richardpauljones/SwiftKueryODBCSQL
