### ISSUE TITLE
RETURNING clause not supported by all databases

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Swift-Kuery#18]
SQLite does not support the `RETURNING` clause.

I suggest that we remove the `Insert.returning()` APIs and make these extensions inside the Postgres driver?

**Comment by ianpartridge** [comment]
There may be issues because the `returningClause` is a stored property, and extensions can only have computed properties. But maybe we could have some sort of `var extensionPoint: [String : Any]` and the Postgres driver adds a `Returning` object to the dictionary?

**Comment by irar2** [comment]
Addressed in #25
