### ISSUE TITLE
SQLite syntax error with HAVING

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Swift-Kuery#22]
```
=======SELECT left(a, 2) as raw FROM tableSelectOSX WHERE b >= 0 GROUP BY tableSelectOSX.a HAVING sum(b) > 3 ORDER BY tableSelectOSX.a DESC=======
Error in query:  near "(": syntax error
```

**Comment by irar2** [comment]
The error is about left(), not about having. The test is created using Raw (left() is not supported by Swift-Kuery), so please either remove the test or change the function to something supported by SQLite.

**Comment by ianpartridge** [comment]
I've removed it for now - thanks.
