### ISSUE TITLE
Subquery returns no rows on SQLite

### ISSUE THREAD

**Issue by ianpartridge** [IBM-Swift/Swift-Kuery#26]
In `TestSubquery.swift`:

```swift
Select(from: t).where((-7).in(Select(t.b, from: t).where(t.b == -1)))
```
is generating:
```sql
SELECT * FROM tableSubquery WHERE -7 IN (SELECT tableSubquery.b FROM tableSubquery WHERE tableSubquery.b = -1)
```

however on SQLite this crashes because `rows` is nil (`"SELECT returned no rows"`).

I'm confused though, because as far as I can see the subquery should return no rows because t.b is never -1?

**Comment by ianpartridge** [comment]
Similarly:

```swift
Select(from: t).group(by: t.a, t.b).having(Parameter().in(Parameter(), Parameter()))
```

is generating:

```sql
SELECT * FROM tableSubquery GROUP BY tableSubquery.a, tableSubquery.b HAVING ?1 IN (?2, ?3)
```

which is returning no rows (instead of 6, as the test expects).

**Comment by irar2** [comment]
```sql
SELECT * FROM tableSubquery GROUP BY tableSubquery.a, tableSubquery.b HAVING ?1 IN (?2, ?3)
```
is actually
```sql
SELECT * FROM tableSubquery GROUP BY tableSubquery.a, tableSubquery.b HAVING true IN (true, false)
```
and it looks like SQLite doesn't have boolean values. I'll add this to QueryBuilder.

**Comment by irar2** [comment]
```sql
SELECT * FROM tableSubquery WHERE -7 IN (SELECT tableSubquery.b FROM tableSubquery WHERE tableSubquery.b = -1)
```
should return an empty result. Does SQLite always return nil instead of empty result? If so, we just need to change the tests.

>I'm confused though, because as far as I can see the subquery should return no rows because t.b is never -1?
Yes, the subquery should return no rows, as well as the query, and the expected number of rows is 0. Posgres returns an empty result as expected.

**Comment by irar2** [comment]
@ianpartridge Please change the tests in TestSubquery from:
```swift
s = Select(from: t).group(by: t.a, t.b).having(Parameter().in(Parameter(), Parameter()))   
executeQueryWithParameters(query: s, connection: connection, parameters: true, true, false) { 
...

s = Select(from: t).where(false.notIn(Parameter(), Parameter())) 
executeQueryWithParameters(query: s, connection: connection, parameters: true, true) {       
```
to 
```swift
s = Select(from: t).group(by: t.a, t.b).having(Parameter().in(Parameter(), Parameter())) 
executeQueryWithParameters(query: s, connection: connection, parameters: 1, 1, 0) { 
...

s = Select(from: t).where(false.notIn(Parameter(), Parameter())) 
executeQueryWithParameters(query: s, connection: connection, parameters: 1, 1) {       
``` 
 Here we pass booleans as parameters, and SQLite tests should use 1/0 instead of true/false.

**Comment by ianpartridge** [comment]
Ah, the SQLite driver doesn't support parameters at the moment.  I haven't worked out whether that's a limitation of SQLite or the driver.

**Comment by irar2** [comment]
Fixed
