### ISSUE TITLE
Multiple JOIN not supported

### ISSUE THREAD

**Issue by naithar** [IBM-Swift/Swift-Kuery#29]
Atm, creating a query with multiple `join` statements, results in error `Multiple joins`.
Will this be changed or is this on purpose?

Also, is contribution on this project's stage acceptable?

**Comment by irar2** [comment]
We are not against multiple joins, we just don't support them at the moment.

Please wait a week or so. Thanks.

**Comment by naithar** [comment]
Thanks for the info.

**Comment by irar2** [comment]
Let's keep this issue open to remember that multiple joins need to be added.
