### ISSUE TITLE
Can we simplify the asRows property?

### ISSUE THREAD

**Issue by rfdickerson** [IBM-Swift/Swift-Kuery#4]
Right now, the `asRows` property takes the following signature:

```swift
public var asRows: ([String], [[Any?]])? 
```

I propose we change it to:

```swift
public var asRows: [[String: Any]]
```

## Reasons:

- Would make it easier to transform the rows into corresponding objects.
- Would more close match the JSON signatures
- I don't understand why the returned value could be nil. If we want to return an NULL from the database, can't we create a new enum case for that?

## Alternative

```swift
enum SQLValue {
   case double(Double)
   case null
   // ...

public var asRows: [[String: SQLValue]]
}

**Comment by pbohrer** [comment]
I did take Robert's arrayOfDictionaries logic and added it as an extension to QueryResult in my simple example: https://github.ibm.com/pbohrer/swift-kuery-play
To avoid name conflicts, I append .1, .2, etc to the keys if there is a conflict.  In general, I do think having an option to return an array of dictionaries it pretty convenient.  Until we have something better, it might be nice to include in Swift-Kuery as a convenience and that would make my sample really small.

**Comment by irar2** [comment]
@rfdickerson Is it ok to close this issue now?

**Comment by rfdickerson** [comment]
Great! Should I update bookstore then to use #42 ?

**Comment by irar2** [comment]
@rfdickerson Sure, that would be great.
