### ISSUE TITLE
WITH clauses for SELECT

### ISSUE THREAD

**Issue by naithar** [IBM-Swift/Swift-Kuery#40]
Are `WITH` clauses for `select` query in the list of features to be implemented or it's something that expected to be covered with `Raw` queries?

Implementing a sync access for database or at the least `asRows` property as desribed in #4 would certainly help in creating a workaround for missing clause as currently without `Raw` query implementation of workaround leads to callback hell.

**Comment by naithar** [comment]
By sync access i mean that using something like this:

```swift
do {
	let select1 = Select(…)
	withResult = try connection.execute(query: select1)
	let rows = withResult.rows
	let select2 = Select(…).where(table.value == rows.first)
	result = try connection.execute(query: select2)
	…handle last select result…
} catch {
	...handle errors...
}
```

Is much more easier to read and understand then as it is now: 

```swift
let select1 = Select(…)
connection.execute(query: select1) { result in
	guard let set = result.asResultSet else {
		…handle error…
	}

	var rows = resultSet.rows

	guard let row = rows.next(),
		let value = row.first else { //or any other index
			…handle no rows or no value…
	}

	let select2 = Select(…).where(table.value == value)

	connection.execute(query: select2) { _ in
		… handle last select result…
	}
}
```

**Comment by naithar** [comment]
Also is public API changes is acceptable, since Kuery didn't reach 1.0.0 yet?

**Comment by irar2** [comment]
We will probably implement `WITH` once we have `CREATE TABLE`, but this may take some time.

We are considering synchronous access, we need some time to decide on this.

By `asRows`  do you mean to get rows as dictionaries with column names as a key?

API changes are acceptable.

**Comment by naithar** [comment]
Thanks for the answers :)

Yes, by `asRows` i mean an array of dictionaries. This would also simplify the example above to something like:
```swift
let value = resultSet.rows.first["value"]
```


As for the `WITH` clause would syntax like this be acceptable:
```swift
let select1 = Select(...).as("table_name")
let select2 = Select(table.a, table.b, select1.field("a").as("in_a"), from: table)
                    ...some other query clauses...
                    .where(table.c == select1.field("b"))
                    .with(select1)
```

**Comment by irar2** [comment]
I can add an array of dictionaries as suggested in #4 in the last comment.

I need to learn more about `WITH` before I reply.

**Comment by naithar** [comment]
Great, thanks.

**Comment by irar2** [comment]
I am sorry, I was wrong thinking `WITH` is related to `CREATE`.

How about the following syntax:
```swift
class AuxiliaryTable: Table {
    let name = "table_name"
    let a = Column("a")
    let b = Column("b")
    // All the columns returned by the Select inside With
}
let auxTable = AuxiliaryTable()
let q = With(auxTable, as: Select(...))
             .select(table.a, table.b, auxTable.a.as("in_a"), from: table)
             .where(table.c == auxTable.b)
```

**Comment by naithar** [comment]
Your example would remove the need to use `.field(...)`, but would require to implement a nested class. Just checked in playground code like this is running, so i guess it's fine:
```swift
func foo() {
    class a {
        func foo() {
            class b { }
            print("foo")
        }
    }
    a().foo()
}

foo()
```

But in my opinion `WITH` is more like an addition for `Select`, not a query like `Update`, `Delete`. Also postgresql doc states that `Delete` and `Update` query can have a `WITH` clause.  

How about this syntax:
```swift
class AuxiliaryTable: WithTable {
    let name = "alias"
    let a = Column("a")
    let b = Column("b")
    // All the columns returned by the Select inside With
}
let auxTable = AuxiliaryTable(as: Select(...))
let q = Select(table.a, table.b, auxTable.a.as("in_a"), from: table)
                    .where(table.c == auxTable.b)
                    .with(auxTable)
```

**Comment by irar2** [comment]
Yes, it would be better to add `.with` to the existing queries. 
But we try to keep our syntax as close to SQL as possible, and your suggestion changes the order between `WITH` and `SELECT`.

**Comment by naithar** [comment]
If SQL syntax is a priority than would this work without creation of a new query?
```swift
class AuxiliaryTable: WithTable {
    let name = "alias"
    let a = Column("a")
    let b = Column("b")
    // All the columns returned by the Select inside With
}
let auxTable = AuxiliaryTable(as: Select(...))
let q = With(auxTable, ...) //multiple tables
                .do(
                    Select(table.a, table.b, auxTable.a.as("in_a"), from: table) //also Update, Delete
                    .where(table.c == auxTable.b))
```

**Comment by irar2** [comment]
Maybe just 
```swift 
func with(_ auxTable: WithTable..., _ query: Query) -> Query
```
i.e.: 

```swift
class AuxiliaryTable: WithTable {
    let name = "alias"
    let a = Column("a")
    let b = Column("b")
    // All the columns returned by the Select inside With
}
let auxTable = AuxiliaryTable(as: Select(...))
let q = with(auxTable,
                    Select(table.a, table.b, auxTable.a.as("in_a"), from: table) //also Update, Delete
                    .where(table.c == auxTable.b)))
```

**Comment by naithar** [comment]
That's actually pretty good.  
The only problem is that this signature could no work, as it would result in: `missing argument for parameter #2 in call` (just checked it)  
So the result should be either `func with(_ auxTable: WithTable..., query: Query) -> Query` or 
```swift
func with(_ auxTable: WithTable, _ query: Query) -> Query { ... }

func with(_ auxTables: [WithTable], _ query: Query) -> Query { ... }
```

**Comment by irar2** [comment]
We prefer the second option, i.e.
```swift
func with(_ auxTable: WithTable, _ query: Query) -> Query { ... }
func with(_ auxTables: [WithTable], _ query: Query) -> Query { ... }
```

**Comment by irar2** [comment]
Implemented
