### ISSUE TITLE
By default add and use array args rather than var args for filters

### ISSUE THREAD

**Issue by robertjpayne** [IBM-Swift/Swift-Kuery#44]
Sorry the title is a bit hard to explain but currently to do an `IN` filter one must use something like `.where(column.id.in("a", "b", "c"))`. It would be great to be able to also do `.where(column.id.in(["a", "b", "c"]))`.

While raw SQL may be better suited to var args most users will be feeding in ids from previous selects / user input etc and it's impossible to turn a Swift array into a var arg array for calling a function.

**Comment by irar2** [comment]
@robertjpayne Could you please verify if the issue has been fixed
