### ISSUE TITLE
Document Swift-Kuery has no paramenter binding and is not safe from SQL injection.

### ISSUE THREAD

**Issue by robertjpayne** [IBM-Swift/Swift-Kuery#45]
I just did a quick experiment and came to the conclusion that it's *very* easy to inject SQL using Swift-Kuery. Given SQL injection is a major security vulnerability I suggest it be documented as such until such time it is resolved:

```
public class DocumentsTable : Table {
    let tableName = "document"
    let sequence = Column("sequence")
    let id = Column("id")
    let type = Column("type")
    let json = Column("json")
}
public let docs = DocumentsTable()

let builder = QueryBuilder()

let statement = Select(fields: [docs.id, docs.type, docs.json], from: docs).where(docs.id.in("a'); DELETE FROM docs WHERE id IN ('b', 'c"))
print(try statement.build(queryBuilder: builder))
```

Emits:

```
SELECT document.id, document.type, document.json FROM document WHERE document.id IN ('a'); DELETE FROM docs WHERE id IN ('b', 'c')
```

Some drivers may detect the dual statement and prevent it but many would not.

**Comment by irar2** [comment]
The way you created an injection is not specific for Swift-Kuery, it's a general problem with SQL. This is why we have parameters to avoid SQL injections. Instead of directly inserting user defined values, use:
```swift
let statement = Select(fields: [docs.id, docs.type, docs.json], from: docs).where(docs.id.in(Parameter()))
```
This will generate for PostgreSQL:
```sql
SELECT document.id, document.type, document.json FROM document WHERE document.id IN (?1)
```
And later call:
```swift
connection.execute(query: statement, parameters: "a")
```

**Comment by robertjpayne** [comment]
@irar2 ah! I see, I didn't really notice this when reading through the examples so was sort of surprised.
