### ISSUE TITLE
Add missing MySQL driver

### ISSUE THREAD

**Issue by lucianboboc** [IBM-Swift/Swift-Kuery#46]
MySQL is one of the most used databases and a driver is missing.

**Comment by paxinos** [comment]
Up Voting!    I've been using the Postgres driver...  but would prefer to work with MySQL

**Comment by na-gupta** [comment]
@lucianboboc @paxinos We just released a MySQL Kuery plugin: https://github.com/IBM-Swift/SwiftKueryMySQL
