### ISSUE TITLE
Request: Support UUID datatypes

### ISSUE THREAD

**Issue by magnusahlberg** [IBM-Swift/Swift-Kuery#70]
It is generally considered good practice to use UUIDs for exposed table keys to avoid exposing the total number of records in a table or allow a malicious party to enumerate over potentially valid items in the DB. They are also very useful for many different scenarios.

## Queries
Using PostgreSQL as an example, UUIDs are specified using the following notation: `'b07ae461-854e-41bc-aa40-a75900c4be59'::uuid`. Currently this requires a raw query (or partially raw query) to select. I propose that Kuery supports using `UUID` structs or `NSUUID` class instances as input types for `.Select()`.

This would require updating the functions `Utils.packType()` and `Utils.packType(_, queryBuilder:)` with a new case like the following:
```
        case let value as UUID:
            return "'\(value.uuidString))'::uuid"
```

The above code is valid for PostgreSQL, but I would assume that it needs to be overloaded by DB-specific code in each implementation.

## Results
Currently Kuery returns UUIDs as a Data()-type with 16 bytes. It would be helpful to be able to cast the result `as? UUID` or `as? NSUUID`.

As I understand Kuery this is very specific to each DB driver. For PostgreSQL, the OID of the uuid datatype needs to be added to `PostgreSQLType.swift` and `PostgreSQLResultFetcher.convert(_ , row: , column:)` needs to add a new `.case` for this datatype. This function needs to read the raw bytes into a UUID or NSUUID. Example:

```
return data.withUnsafeBytes { (bytes: UnsafePointer<UInt8>) -> NSUUID in
    return NSUUID(uuidBytes: bytes)
}
```

## Considerations
It should be considered wether to use NSUUID or UUID as the input/result object. This is way beyond my competence. The only caveat I've seen is that UUIDs will need to be initialized with a tuple of 16 `UInt8`s, which is a pain. NSUUID can be initialized with a `UnsafePointer<UInt8>` which seems a little more straightforward.

**Comment by irar2** [comment]
I checked the databases we support, and it looks like only Postgres fully supports UUIDs. MySQL and and DB2 seem to be able to generate UUID, but don't have a type for it. And SQLite has no support at all. 

It is easy to use UUID as input, because we just pass parameters as Any, but getting the result object as UUID will work only for Postgres.

Since we are trying to keep Swift-Kuery as db-independant as possible, adding UUID support seems to break the abstraction too much.

**Comment by magnusahlberg** [comment]
I see your point. Perhaps a way to go about it then, on the Query-side, would be to allow a method to enter Raw data into a query with named/numbered parameters. So that one could add `'58fba7e2-5528-4121-80ff-aee405706c45'::uuid` as a named/numbered parameter. If this is already possible, I apologize – I could not figure it out.

On the result-side however, all changes I am suggesting would be done in the Kuery-Postgres implementation. It would help a great deal as currently, the only way to use UUID:s today in a useable way is to run .map() on the `resultset.asRows`, copying the entire result set and replacing the columns that are of the `Data`-type with corresponding `NSUUID` objects.

I'm hoping this would be a manageable way forward.

**Comment by irar2** [comment]
Please check the above commit. It handles UUID in the result fetcher and returns its String value. I also added a test that inserts UUID.uuidString.

**Comment by magnusahlberg** [comment]
From my testing this works exactly as expected. Fantastic!
