### ISSUE TITLE
QueryFilterProtocol custom function name

### ISSUE THREAD

**Issue by GiacomoLeopizzi** [IBM-Swift/Swift-Kuery#72]
Is it possible to implement the possibility to have custom function names for QueryFilterProtocol? 
For example my query require a where with UNIX_TIMESTAMP(column) and I can not achieve this now...

**Comment by irar2** [comment]
You can write your `where` expression as a raw String:
``` swift
s = Select(*, from: t)
      .where("UNIX_TIMESTAMP(column) ...")
```

**Comment by GiacomoLeopizzi** [comment]
Thank you so much!
