### ISSUE TITLE
Build error when building within Xcode or AppCode

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/Swift-Kuery#75]
I have an app that uses SwiftKuery. The app builds successfully from the command line:

```
$ swift build
```

However, when I try to build from within Xcode (or AppCode), I get the following errors:

```
Use of undeclared type 'IndexColumn'  Column.swift
Use of undeclared type 'SQLDataType'  Column.swift
```

I use Xcode 8.3.2

**Comment by shmuelk** [comment]
Did you have it building before from XCode and recently updated the version of Swift-Kuery you are using?

If so, please regenerate your XCode project, by running `swift package generate-xcodeproj`

**Comment by gmosx** [comment]
Thanks, that solved the problem!
