### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by irar2** [IBM-Swift/Swift-Kuery#79]

**Comment by djones6** [comment]
We measured the changes from the issue_79 branches and saw improvement: https://github.ibm.com/IBM-Swift/Performance/issues/30
However the later changes for Prepared Statements didn't achieve the same level of performance (in fact no improvement at all, @shmuelk and @irar2 were investigating).

Please can we document what additional work we're planning to do to address the Kuery <-> Raw gap?

**Comment by kilnerm** [comment]
I have opened https://github.com/IBM-Swift/Swift-Kuery/issues/156 to address the first part of these changes.

Closing this work item.
