### ISSUE TITLE
Insert NULL into the database

### ISSUE THREAD

**Issue by damir-sirola** [IBM-Swift/Swift-Kuery#80]
Hi, I'm wondering how I can insert null into database.
I checked the examples and tests, but it doesn't appear anywhere.

I'm using multiple rows insert and the code looks something like this

```
let rows = usersToSave.map { user -> [Any] in
    return [user.id, user.username, user.password as Any, user.passwordResetToken as Any]
}
let insertUsers = Insert(
    into: users,
    columns: [users.id, users.username, users.password, users.passwordResetToken],
    rows: rows
)
```

Password and passwordResetToken are optionals.
When I execute the query it reports the following error:
    `Query execution error: ERROR:  column "nil" does not exist`

I also tried to specify NULL as string, but that just inserts the text "NULL"
`user.password as Any` -> `user.password ?? "NULL"`

I tried to do full text search on the project but didn't find anything that looked relevant.

If there is a way to do this I think it would be helpful to add an example to documentation.

**Comment by irar2** [comment]
You can pass `nil` as parameter. Something like:

```swift
let rows = usersToSave.map { user -> [Any] in
    return [user.id, user.username, Parameter("password"), Parameter("passwordResetToken")]
}
...
connection.execute(query: insertUsers, parameters: ["password" : user.password, "passwordResetToken" : user.passwordResetToken])
```

Does it work for you?

**Comment by damir-sirola** [comment]
Yes, that works! And everything that is in parameters is safe from SQL injection, right?
Thank you for your help!

**Comment by irar2** [comment]
Great!
Yes, the parameters are safe from SQL injection.
