### ISSUE TITLE
Create at, Updated at and soft Delete

### ISSUE THREAD

**Issue by BugsBunnyBR** [IBM-Swift/Swift-Kuery#87]
Hi, would it be possible to have soft delete implemented ?
Also `created_at`and `updated_at` support would be nice.

This [gist ](https://gist.github.com/logrusorgru/82b002b8807253b2adef) shows that the usage of timestamps for `created_at`and `updated_at` are  supported in many databases (Mysql, Postgresql, Sqlite) in the create schema.

**Comment by kilnerm** [comment]
Soft delete is not a function that is provided at the database layer, like in the example above it is achieved via your schema and query execution. As such soft delete is not something I believe should be considered for implementation.

The following issues have been opened to address created_at and updated_at:

https://github.com/IBM-Swift/Swift-Kuery/issues/154
https://github.com/IBM-Swift/Swift-Kuery/issues/155

I am marking this as closed.
