### ISSUE TITLE
Table.drop() does not work with KueryMySQL

### ISSUE THREAD

**Issue by andreasmalik** [IBM-Swift/Swift-Kuery#90]
Hello,

I'm trying to drop an MySQL-table with the example structure and Kuery MySQL 0.13:

`
class Grades: Table {
    let tableName = "Grades"
    let id = Column("id", Int16.self, length: 6, primaryKey: true)
    let course = Column("course", Varchar.self, length: 50)
    let grade = Column("grade", Int16.self, check: "grade >= 0")
}
`

When I'm tryping to drop the table now, I'm getting an wrong query

`
let grades = Grades();
Log.verbose( "Dropping old table with \(grades.drop().query)" );
`

`grades.drop().query` should return `DROP TABLE Grades` but returns `DROP TABLE`.

I have a workaround with

    let dropGradesTableSQL: String = "DROP TABLE \(grades.tableName)";
    
    Log.verbose( "Dropping old table with \(dropGradesTableSQL)" );
    
    // Trying to drop the old table
    connection.execute( dropGradesTableSQL )
    {
    
        result in
        
        guard result.success else
        {
            
            Log.error( "Failed to drop table: \(result.asError!) with \(dropGradesTableSQL)" );
            
            return;
            
        }
        
    }

**Comment by irar2** [comment]
`grades.drop()` returns a `Raw` query that has two fields `query` and `tables`. `query` in this case is `DROP TABLE`,  and `tables` is `[grades]`.

To execute the drop query you can use `grades.drop().execute(connection)`.

**Comment by andreasmalik** [comment]
Thanks for the reply. It makes sense and work with grades.drop().execute(connection).
