### ISSUE TITLE
Support many-to-many tables with foreign keys

### ISSUE THREAD

**Issue by bridger** [IBM-Swift/Swift-Kuery#94]
I'm trying to make a table which relates two other tables in a many-to-many relationship. I've got a Documents table and a Users table. Now I'm trying to make a DocumentUsers table which relates them both.

It is similar to the answer here: https://stackoverflow.com/a/9790225

However, I can't make a foreign key to both the Documents table and the Users table. This constraint fails:

`documentUsers.foreignKey([documentUsers.documentId, documentUsers.userId], references: [documents.documentId, users.userId])`

The error is `Foreign key references columns from more than one table.`, which I think is a false positive.

Please excuse me if I'm just going about this the wrong way... I'm not totally sure if I've got the right approach.

**Comment by LoiKos** [comment]
this is an important miss ! I have the same issue ... even you did it wrong because you want to create 2 foreign not one on 2 elements I think. 
I think the good way is : 
```swift
documentUsers.foreignKey(documentUsers.documentId, references: documents.documentId)
documentUsers.foreignKey(documentUsers.userId, references: users.userId)
```
but even if you do this way you gonna throw because it's not implemented yet. that what I understand from the code. If it's possible to add multiple foreign, could it be explain in the documentation ?
👍 Need update
@irar2

**Comment by AKazm** [comment]
This is obviously still an issue. Any updates on this?

**Comment by kilnerm** [comment]
I have picked this issue up today and have written a test case to replicate the problem.
I will look to address both the above issues through the fix and will update once I have something working.

**Comment by kilnerm** [comment]
SwiftKuery 2.0.0 now has support for multiple foreign keys.

To add multiple keys to a table use multiple calls to either API, eg.

```
documentUsers.foreignKey(documentUsers.documentId, references: documents.documentId)
documentUsers.foreignKey(documentUsers.userId, references: users.userId)
```
The following example from the original issue report will still flag as it is invalid to specify reference columns from different tables.

@bridger if you can give the new support a test and let me know if it all works for you it would be great.

**Comment by wafflespeanut** [comment]
@kilnerm Thanks! Adding multiple keys to the `Table` API looks intuitive and works fine :)
