### ISSUE TITLE
SQL Injection Vulnerabilities

### ISSUE THREAD

**Issue by bridger** [IBM-Swift/Swift-Kuery#97]
Strings are not properly escaped in sql queries when not using parameters. This was a huge surprise to me after developing with Kuery for a while and accidentally writing a lot of vulnerable code.

For example, this query:
```
let studentName = "Robert'); DROP TABLE students; --"
let addUser = Insert(into: students, columns: [students.name], values: [studentName])
```
Will be executed as:

`INSERT INTO students (name) VALUES ('Robert'); DROP TABLE students; --')`

Similar injection attacks are possible when using a string directly in a `where`.

Using `Parameter` avoids this issue but it isn't clear from the docs that not using Parameters leaves one open to injection attacks. This is a pretty big deal!

I'd suggest that the docs be updated ASAP to add an unmissable disclaimer that user inputs *must* be put into queries through the `Parameter` API.

Still, I think this will be a common vulnerability for devs to accidentally leave open when using Kuery. A longer-term solution would be to do proper escaping or maybe translate all strings into `Parameters` automatically. Without that, maybe it would be best to rename some methods to add `unsafe` to the parameter names so it is clear when something is open to injection attacks.

**Comment by na-gupta** [comment]
Added a [section](https://github.com/IBM-Swift/Swift-Kuery#sql-injection-prevention-using-parameterization) for this. Thanks.
